import { UqExt as Uq } from './JkPlatformjoint';
import * as Platform from './Platform.ui';
import * as City from './City.ui';
import * as County from './County.ui';
import * as Province from './Province.ui';
import * as JDCity from './JDCity.ui';
import * as JDCounty from './JDCounty.ui';
import * as JDTown from './JDTown.ui';
import * as JDProvince from './JDProvince.ui';
import * as PlatformCustomer from './PlatformCustomer.ui';
import * as Customer from './Customer.ui';
import * as EpecProvince from './EpecProvince.ui';
import * as EpecCity from './EpecCity.ui';
import * as EpecCounty from './EpecCounty.ui';
import * as WebUser from './WebUser.ui';
import * as EpecMessage from './EpecMessage.ui';
import * as EpecMessageData from './EpecMessageData.ui';
import * as ApiRawContent from './ApiRawContent.ui';
import * as ExpressLogistics from './ExpressLogistics.ui';
import * as PunchoutSetupRequest from './PunchoutSetupRequest.ui';
import * as Organization from './Organization.ui';

export function setUI(uq: Uq) {
	Object.assign(uq.Platform, Platform);
	Object.assign(uq.City, City);
	Object.assign(uq.County, County);
	Object.assign(uq.Province, Province);
	Object.assign(uq.JDCity, JDCity);
	Object.assign(uq.JDCounty, JDCounty);
	Object.assign(uq.JDTown, JDTown);
	Object.assign(uq.JDProvince, JDProvince);
	Object.assign(uq.PlatformCustomer, PlatformCustomer);
	Object.assign(uq.Customer, Customer);
	Object.assign(uq.EpecProvince, EpecProvince);
	Object.assign(uq.EpecCity, EpecCity);
	Object.assign(uq.EpecCounty, EpecCounty);
	Object.assign(uq.WebUser, WebUser);
	Object.assign(uq.EpecMessage, EpecMessage);
	Object.assign(uq.EpecMessageData, EpecMessageData);
	Object.assign(uq.ApiRawContent, ApiRawContent);
	Object.assign(uq.ExpressLogistics, ExpressLogistics);
	Object.assign(uq.PunchoutSetupRequest, PunchoutSetupRequest);
	Object.assign(uq.Organization, Organization);
}
export * from './JkPlatformjoint';
