import { UqExt as Uq } from './JkWebuser';
import * as InvoiceInfo from './InvoiceInfo.ui';
import * as Address from './Address.ui';
import * as SalesRegion from './SalesRegion.ui';
import * as County from './County.ui';
import * as Customer from './Customer.ui';
import * as WebUser from './WebUser.ui';
import * as AuditPendingUserRefuseReason from './AuditPendingUserRefuseReason.ui';
import * as City from './City.ui';
import * as InvoiceType from './InvoiceType.ui';
import * as BuyerAccount from './BuyerAccount.ui';
import * as Currency from './Currency.ui';
import * as Country from './Country.ui';
import * as Province from './Province.ui';
import * as Contact from './Contact.ui';
import * as WebUserSettingType from './WebUserSettingType.ui';
import * as VIPCardType from './VIPCardType.ui';
import * as ProductX from './ProductX.ui';
import * as Brand from './Brand.ui';
import * as Chemical from './Chemical.ui';

export function setUI(uq: Uq) {
	Object.assign(uq.InvoiceInfo, InvoiceInfo);
	Object.assign(uq.Address, Address);
	Object.assign(uq.SalesRegion, SalesRegion);
	Object.assign(uq.County, County);
	Object.assign(uq.Customer, Customer);
	Object.assign(uq.WebUser, WebUser);
	Object.assign(uq.AuditPendingUserRefuseReason, AuditPendingUserRefuseReason);
	Object.assign(uq.City, City);
	Object.assign(uq.InvoiceType, InvoiceType);
	Object.assign(uq.BuyerAccount, BuyerAccount);
	Object.assign(uq.Currency, Currency);
	Object.assign(uq.Country, Country);
	Object.assign(uq.Province, Province);
	Object.assign(uq.Contact, Contact);
	Object.assign(uq.WebUserSettingType, WebUserSettingType);
	Object.assign(uq.VIPCardType, VIPCardType);
	Object.assign(uq.ProductX, ProductX);
	Object.assign(uq.Brand, Brand);
	Object.assign(uq.Chemical, Chemical);
}
export * from './JkWebuser';
